package com.softwerke.nrv.newsapaper.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.softwerke.nrv.newsapaper.model.UserComment;
import com.softwerke.nrv.newsapaper.service.UserCommentLocalServiceUtil;

/**
 * The extended model base implementation for the UserComment service. Represents a row in the &quot;usercomment_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UserCommentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserCommentImpl
 * @see com.softwerke.nrv.newsapaper.model.UserComment
 * @generated
 */
public abstract class UserCommentBaseImpl extends UserCommentModelImpl
    implements UserComment {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a user comment model instance should use the {@link UserComment} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            UserCommentLocalServiceUtil.addUserComment(this);
        } else {
            UserCommentLocalServiceUtil.updateUserComment(this);
        }
    }
}
