package com.softwerke.nrv.newsapaper.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the NewsArticle service. Represents a row in the &quot;newsartcile_data&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.softwerke.nrv.newsapaper.model.impl.NewsArticleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.softwerke.nrv.newsapaper.model.impl.NewsArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsArticle
 * @see com.softwerke.nrv.newsapaper.model.impl.NewsArticleImpl
 * @see com.softwerke.nrv.newsapaper.model.impl.NewsArticleModelImpl
 * @generated
 */
public interface NewsArticleModel extends BaseModel<NewsArticle> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a news article model instance should use the {@link NewsArticle} interface instead.
     */

    /**
     * Returns the primary key of this news article.
     *
     * @return the primary key of this news article
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this news article.
     *
     * @param primaryKey the primary key of this news article
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the article ID of this news article.
     *
     * @return the article ID of this news article
     */
    public long getArticleId();

    /**
     * Sets the article ID of this news article.
     *
     * @param articleId the article ID of this news article
     */
    public void setArticleId(long articleId);

    /**
     * Returns the author of this news article.
     *
     * @return the author of this news article
     */
    @AutoEscape
    public String getAuthor();

    /**
     * Sets the author of this news article.
     *
     * @param author the author of this news article
     */
    public void setAuthor(String author);

    /**
     * Returns the title of this news article.
     *
     * @return the title of this news article
     */
    @AutoEscape
    public String getTitle();

    /**
     * Sets the title of this news article.
     *
     * @param title the title of this news article
     */
    public void setTitle(String title);

    /**
     * Returns the content of this news article.
     *
     * @return the content of this news article
     */
    @AutoEscape
    public String getContent();

    /**
     * Sets the content of this news article.
     *
     * @param content the content of this news article
     */
    public void setContent(String content);

    /**
     * Returns the status of this news article.
     *
     * @return the status of this news article
     */
    public int getStatus();

    /**
     * Sets the status of this news article.
     *
     * @param status the status of this news article
     */
    public void setStatus(int status);

    /**
     * Returns the create date of this news article.
     *
     * @return the create date of this news article
     */
    public Date getCreateDate();

    /**
     * Sets the create date of this news article.
     *
     * @param createDate the create date of this news article
     */
    public void setCreateDate(Date createDate);

    /**
     * Returns the editor comment of this news article.
     *
     * @return the editor comment of this news article
     */
    @AutoEscape
    public String getEditorComment();

    /**
     * Sets the editor comment of this news article.
     *
     * @param editorComment the editor comment of this news article
     */
    public void setEditorComment(String editorComment);

    /**
     * Returns the update date of this news article.
     *
     * @return the update date of this news article
     */
    public Date getUpdateDate();

    /**
     * Sets the update date of this news article.
     *
     * @param updateDate the update date of this news article
     */
    public void setUpdateDate(Date updateDate);

    /**
     * Returns the author ID of this news article.
     *
     * @return the author ID of this news article
     */
    public long getAuthorId();

    /**
     * Sets the author ID of this news article.
     *
     * @param authorId the author ID of this news article
     */
    public void setAuthorId(long authorId);

    /**
     * Returns the image url of this news article.
     *
     * @return the image url of this news article
     */
    @AutoEscape
    public String getImageUrl();

    /**
     * Sets the image url of this news article.
     *
     * @param imageUrl the image url of this news article
     */
    public void setImageUrl(String imageUrl);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.softwerke.nrv.newsapaper.model.NewsArticle newsArticle);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.softwerke.nrv.newsapaper.model.NewsArticle> toCacheModel();

    @Override
    public com.softwerke.nrv.newsapaper.model.NewsArticle toEscapedModel();

    @Override
    public com.softwerke.nrv.newsapaper.model.NewsArticle toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
